// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package org.example.stubs;

public final class Bank {
  private Bank() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConvertCurrencyRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConvertCurrencyRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string currencyFrom = 1;</code>
     * @return The currencyFrom.
     */
    java.lang.String getCurrencyFrom();
    /**
     * <code>string currencyFrom = 1;</code>
     * @return The bytes for currencyFrom.
     */
    com.google.protobuf.ByteString
        getCurrencyFromBytes();

    /**
     * <code>string currencyTo = 2;</code>
     * @return The currencyTo.
     */
    java.lang.String getCurrencyTo();
    /**
     * <code>string currencyTo = 2;</code>
     * @return The bytes for currencyTo.
     */
    com.google.protobuf.ByteString
        getCurrencyToBytes();

    /**
     * <code>float amount = 3;</code>
     * @return The amount.
     */
    float getAmount();
  }
  /**
   * Protobuf type {@code ConvertCurrencyRequest}
   */
  public  static final class ConvertCurrencyRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConvertCurrencyRequest)
      ConvertCurrencyRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConvertCurrencyRequest.newBuilder() to construct.
    private ConvertCurrencyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConvertCurrencyRequest() {
      currencyFrom_ = "";
      currencyTo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConvertCurrencyRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConvertCurrencyRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              currencyFrom_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              currencyTo_ = s;
              break;
            }
            case 29: {

              amount_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.stubs.Bank.internal_static_ConvertCurrencyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.stubs.Bank.internal_static_ConvertCurrencyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.stubs.Bank.ConvertCurrencyRequest.class, org.example.stubs.Bank.ConvertCurrencyRequest.Builder.class);
    }

    public static final int CURRENCYFROM_FIELD_NUMBER = 1;
    private volatile java.lang.Object currencyFrom_;
    /**
     * <code>string currencyFrom = 1;</code>
     * @return The currencyFrom.
     */
    public java.lang.String getCurrencyFrom() {
      java.lang.Object ref = currencyFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currencyFrom_ = s;
        return s;
      }
    }
    /**
     * <code>string currencyFrom = 1;</code>
     * @return The bytes for currencyFrom.
     */
    public com.google.protobuf.ByteString
        getCurrencyFromBytes() {
      java.lang.Object ref = currencyFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currencyFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENCYTO_FIELD_NUMBER = 2;
    private volatile java.lang.Object currencyTo_;
    /**
     * <code>string currencyTo = 2;</code>
     * @return The currencyTo.
     */
    public java.lang.String getCurrencyTo() {
      java.lang.Object ref = currencyTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currencyTo_ = s;
        return s;
      }
    }
    /**
     * <code>string currencyTo = 2;</code>
     * @return The bytes for currencyTo.
     */
    public com.google.protobuf.ByteString
        getCurrencyToBytes() {
      java.lang.Object ref = currencyTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currencyTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private float amount_;
    /**
     * <code>float amount = 3;</code>
     * @return The amount.
     */
    public float getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCurrencyFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currencyFrom_);
      }
      if (!getCurrencyToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, currencyTo_);
      }
      if (amount_ != 0F) {
        output.writeFloat(3, amount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCurrencyFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currencyFrom_);
      }
      if (!getCurrencyToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, currencyTo_);
      }
      if (amount_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, amount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.stubs.Bank.ConvertCurrencyRequest)) {
        return super.equals(obj);
      }
      org.example.stubs.Bank.ConvertCurrencyRequest other = (org.example.stubs.Bank.ConvertCurrencyRequest) obj;

      if (!getCurrencyFrom()
          .equals(other.getCurrencyFrom())) return false;
      if (!getCurrencyTo()
          .equals(other.getCurrencyTo())) return false;
      if (java.lang.Float.floatToIntBits(getAmount())
          != java.lang.Float.floatToIntBits(
              other.getAmount())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENCYFROM_FIELD_NUMBER;
      hash = (53 * hash) + getCurrencyFrom().hashCode();
      hash = (37 * hash) + CURRENCYTO_FIELD_NUMBER;
      hash = (53 * hash) + getCurrencyTo().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAmount());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.stubs.Bank.ConvertCurrencyRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.stubs.Bank.ConvertCurrencyRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.stubs.Bank.ConvertCurrencyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.stubs.Bank.ConvertCurrencyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.stubs.Bank.ConvertCurrencyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.stubs.Bank.ConvertCurrencyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.stubs.Bank.ConvertCurrencyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.stubs.Bank.ConvertCurrencyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.stubs.Bank.ConvertCurrencyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.stubs.Bank.ConvertCurrencyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.stubs.Bank.ConvertCurrencyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.stubs.Bank.ConvertCurrencyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.stubs.Bank.ConvertCurrencyRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConvertCurrencyRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConvertCurrencyRequest)
        org.example.stubs.Bank.ConvertCurrencyRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.stubs.Bank.internal_static_ConvertCurrencyRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.stubs.Bank.internal_static_ConvertCurrencyRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.stubs.Bank.ConvertCurrencyRequest.class, org.example.stubs.Bank.ConvertCurrencyRequest.Builder.class);
      }

      // Construct using org.example.stubs.Bank.ConvertCurrencyRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currencyFrom_ = "";

        currencyTo_ = "";

        amount_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.stubs.Bank.internal_static_ConvertCurrencyRequest_descriptor;
      }

      @java.lang.Override
      public org.example.stubs.Bank.ConvertCurrencyRequest getDefaultInstanceForType() {
        return org.example.stubs.Bank.ConvertCurrencyRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.stubs.Bank.ConvertCurrencyRequest build() {
        org.example.stubs.Bank.ConvertCurrencyRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.stubs.Bank.ConvertCurrencyRequest buildPartial() {
        org.example.stubs.Bank.ConvertCurrencyRequest result = new org.example.stubs.Bank.ConvertCurrencyRequest(this);
        result.currencyFrom_ = currencyFrom_;
        result.currencyTo_ = currencyTo_;
        result.amount_ = amount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.stubs.Bank.ConvertCurrencyRequest) {
          return mergeFrom((org.example.stubs.Bank.ConvertCurrencyRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.stubs.Bank.ConvertCurrencyRequest other) {
        if (other == org.example.stubs.Bank.ConvertCurrencyRequest.getDefaultInstance()) return this;
        if (!other.getCurrencyFrom().isEmpty()) {
          currencyFrom_ = other.currencyFrom_;
          onChanged();
        }
        if (!other.getCurrencyTo().isEmpty()) {
          currencyTo_ = other.currencyTo_;
          onChanged();
        }
        if (other.getAmount() != 0F) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.stubs.Bank.ConvertCurrencyRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.stubs.Bank.ConvertCurrencyRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object currencyFrom_ = "";
      /**
       * <code>string currencyFrom = 1;</code>
       * @return The currencyFrom.
       */
      public java.lang.String getCurrencyFrom() {
        java.lang.Object ref = currencyFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currencyFrom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currencyFrom = 1;</code>
       * @return The bytes for currencyFrom.
       */
      public com.google.protobuf.ByteString
          getCurrencyFromBytes() {
        java.lang.Object ref = currencyFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currencyFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currencyFrom = 1;</code>
       * @param value The currencyFrom to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currencyFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currencyFrom = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrencyFrom() {
        
        currencyFrom_ = getDefaultInstance().getCurrencyFrom();
        onChanged();
        return this;
      }
      /**
       * <code>string currencyFrom = 1;</code>
       * @param value The bytes for currencyFrom to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currencyFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object currencyTo_ = "";
      /**
       * <code>string currencyTo = 2;</code>
       * @return The currencyTo.
       */
      public java.lang.String getCurrencyTo() {
        java.lang.Object ref = currencyTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currencyTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currencyTo = 2;</code>
       * @return The bytes for currencyTo.
       */
      public com.google.protobuf.ByteString
          getCurrencyToBytes() {
        java.lang.Object ref = currencyTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currencyTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currencyTo = 2;</code>
       * @param value The currencyTo to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currencyTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currencyTo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrencyTo() {
        
        currencyTo_ = getDefaultInstance().getCurrencyTo();
        onChanged();
        return this;
      }
      /**
       * <code>string currencyTo = 2;</code>
       * @param value The bytes for currencyTo to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currencyTo_ = value;
        onChanged();
        return this;
      }

      private float amount_ ;
      /**
       * <code>float amount = 3;</code>
       * @return The amount.
       */
      public float getAmount() {
        return amount_;
      }
      /**
       * <code>float amount = 3;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(float value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float amount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        
        amount_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConvertCurrencyRequest)
    }

    // @@protoc_insertion_point(class_scope:ConvertCurrencyRequest)
    private static final org.example.stubs.Bank.ConvertCurrencyRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.stubs.Bank.ConvertCurrencyRequest();
    }

    public static org.example.stubs.Bank.ConvertCurrencyRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConvertCurrencyRequest>
        PARSER = new com.google.protobuf.AbstractParser<ConvertCurrencyRequest>() {
      @java.lang.Override
      public ConvertCurrencyRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConvertCurrencyRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConvertCurrencyRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConvertCurrencyRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.stubs.Bank.ConvertCurrencyRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConvertCurrencyResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConvertCurrencyResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string currencyFrom = 1;</code>
     * @return The currencyFrom.
     */
    java.lang.String getCurrencyFrom();
    /**
     * <code>string currencyFrom = 1;</code>
     * @return The bytes for currencyFrom.
     */
    com.google.protobuf.ByteString
        getCurrencyFromBytes();

    /**
     * <code>string currencyTo = 2;</code>
     * @return The currencyTo.
     */
    java.lang.String getCurrencyTo();
    /**
     * <code>string currencyTo = 2;</code>
     * @return The bytes for currencyTo.
     */
    com.google.protobuf.ByteString
        getCurrencyToBytes();

    /**
     * <code>float amount = 3;</code>
     * @return The amount.
     */
    float getAmount();

    /**
     * <code>float result = 4;</code>
     * @return The result.
     */
    float getResult();
  }
  /**
   * Protobuf type {@code ConvertCurrencyResponse}
   */
  public  static final class ConvertCurrencyResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConvertCurrencyResponse)
      ConvertCurrencyResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConvertCurrencyResponse.newBuilder() to construct.
    private ConvertCurrencyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConvertCurrencyResponse() {
      currencyFrom_ = "";
      currencyTo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConvertCurrencyResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConvertCurrencyResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              currencyFrom_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              currencyTo_ = s;
              break;
            }
            case 29: {

              amount_ = input.readFloat();
              break;
            }
            case 37: {

              result_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.stubs.Bank.internal_static_ConvertCurrencyResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.stubs.Bank.internal_static_ConvertCurrencyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.stubs.Bank.ConvertCurrencyResponse.class, org.example.stubs.Bank.ConvertCurrencyResponse.Builder.class);
    }

    public static final int CURRENCYFROM_FIELD_NUMBER = 1;
    private volatile java.lang.Object currencyFrom_;
    /**
     * <code>string currencyFrom = 1;</code>
     * @return The currencyFrom.
     */
    public java.lang.String getCurrencyFrom() {
      java.lang.Object ref = currencyFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currencyFrom_ = s;
        return s;
      }
    }
    /**
     * <code>string currencyFrom = 1;</code>
     * @return The bytes for currencyFrom.
     */
    public com.google.protobuf.ByteString
        getCurrencyFromBytes() {
      java.lang.Object ref = currencyFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currencyFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENCYTO_FIELD_NUMBER = 2;
    private volatile java.lang.Object currencyTo_;
    /**
     * <code>string currencyTo = 2;</code>
     * @return The currencyTo.
     */
    public java.lang.String getCurrencyTo() {
      java.lang.Object ref = currencyTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currencyTo_ = s;
        return s;
      }
    }
    /**
     * <code>string currencyTo = 2;</code>
     * @return The bytes for currencyTo.
     */
    public com.google.protobuf.ByteString
        getCurrencyToBytes() {
      java.lang.Object ref = currencyTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currencyTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private float amount_;
    /**
     * <code>float amount = 3;</code>
     * @return The amount.
     */
    public float getAmount() {
      return amount_;
    }

    public static final int RESULT_FIELD_NUMBER = 4;
    private float result_;
    /**
     * <code>float result = 4;</code>
     * @return The result.
     */
    public float getResult() {
      return result_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCurrencyFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currencyFrom_);
      }
      if (!getCurrencyToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, currencyTo_);
      }
      if (amount_ != 0F) {
        output.writeFloat(3, amount_);
      }
      if (result_ != 0F) {
        output.writeFloat(4, result_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCurrencyFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currencyFrom_);
      }
      if (!getCurrencyToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, currencyTo_);
      }
      if (amount_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, amount_);
      }
      if (result_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.stubs.Bank.ConvertCurrencyResponse)) {
        return super.equals(obj);
      }
      org.example.stubs.Bank.ConvertCurrencyResponse other = (org.example.stubs.Bank.ConvertCurrencyResponse) obj;

      if (!getCurrencyFrom()
          .equals(other.getCurrencyFrom())) return false;
      if (!getCurrencyTo()
          .equals(other.getCurrencyTo())) return false;
      if (java.lang.Float.floatToIntBits(getAmount())
          != java.lang.Float.floatToIntBits(
              other.getAmount())) return false;
      if (java.lang.Float.floatToIntBits(getResult())
          != java.lang.Float.floatToIntBits(
              other.getResult())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENCYFROM_FIELD_NUMBER;
      hash = (53 * hash) + getCurrencyFrom().hashCode();
      hash = (37 * hash) + CURRENCYTO_FIELD_NUMBER;
      hash = (53 * hash) + getCurrencyTo().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAmount());
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getResult());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.stubs.Bank.ConvertCurrencyResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.stubs.Bank.ConvertCurrencyResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.stubs.Bank.ConvertCurrencyResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.stubs.Bank.ConvertCurrencyResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.stubs.Bank.ConvertCurrencyResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.stubs.Bank.ConvertCurrencyResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.stubs.Bank.ConvertCurrencyResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.stubs.Bank.ConvertCurrencyResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.stubs.Bank.ConvertCurrencyResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.stubs.Bank.ConvertCurrencyResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.stubs.Bank.ConvertCurrencyResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.stubs.Bank.ConvertCurrencyResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.stubs.Bank.ConvertCurrencyResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConvertCurrencyResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConvertCurrencyResponse)
        org.example.stubs.Bank.ConvertCurrencyResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.stubs.Bank.internal_static_ConvertCurrencyResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.stubs.Bank.internal_static_ConvertCurrencyResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.stubs.Bank.ConvertCurrencyResponse.class, org.example.stubs.Bank.ConvertCurrencyResponse.Builder.class);
      }

      // Construct using org.example.stubs.Bank.ConvertCurrencyResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currencyFrom_ = "";

        currencyTo_ = "";

        amount_ = 0F;

        result_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.stubs.Bank.internal_static_ConvertCurrencyResponse_descriptor;
      }

      @java.lang.Override
      public org.example.stubs.Bank.ConvertCurrencyResponse getDefaultInstanceForType() {
        return org.example.stubs.Bank.ConvertCurrencyResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.stubs.Bank.ConvertCurrencyResponse build() {
        org.example.stubs.Bank.ConvertCurrencyResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.stubs.Bank.ConvertCurrencyResponse buildPartial() {
        org.example.stubs.Bank.ConvertCurrencyResponse result = new org.example.stubs.Bank.ConvertCurrencyResponse(this);
        result.currencyFrom_ = currencyFrom_;
        result.currencyTo_ = currencyTo_;
        result.amount_ = amount_;
        result.result_ = result_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.stubs.Bank.ConvertCurrencyResponse) {
          return mergeFrom((org.example.stubs.Bank.ConvertCurrencyResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.stubs.Bank.ConvertCurrencyResponse other) {
        if (other == org.example.stubs.Bank.ConvertCurrencyResponse.getDefaultInstance()) return this;
        if (!other.getCurrencyFrom().isEmpty()) {
          currencyFrom_ = other.currencyFrom_;
          onChanged();
        }
        if (!other.getCurrencyTo().isEmpty()) {
          currencyTo_ = other.currencyTo_;
          onChanged();
        }
        if (other.getAmount() != 0F) {
          setAmount(other.getAmount());
        }
        if (other.getResult() != 0F) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.stubs.Bank.ConvertCurrencyResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.stubs.Bank.ConvertCurrencyResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object currencyFrom_ = "";
      /**
       * <code>string currencyFrom = 1;</code>
       * @return The currencyFrom.
       */
      public java.lang.String getCurrencyFrom() {
        java.lang.Object ref = currencyFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currencyFrom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currencyFrom = 1;</code>
       * @return The bytes for currencyFrom.
       */
      public com.google.protobuf.ByteString
          getCurrencyFromBytes() {
        java.lang.Object ref = currencyFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currencyFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currencyFrom = 1;</code>
       * @param value The currencyFrom to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currencyFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currencyFrom = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrencyFrom() {
        
        currencyFrom_ = getDefaultInstance().getCurrencyFrom();
        onChanged();
        return this;
      }
      /**
       * <code>string currencyFrom = 1;</code>
       * @param value The bytes for currencyFrom to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currencyFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object currencyTo_ = "";
      /**
       * <code>string currencyTo = 2;</code>
       * @return The currencyTo.
       */
      public java.lang.String getCurrencyTo() {
        java.lang.Object ref = currencyTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currencyTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currencyTo = 2;</code>
       * @return The bytes for currencyTo.
       */
      public com.google.protobuf.ByteString
          getCurrencyToBytes() {
        java.lang.Object ref = currencyTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currencyTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currencyTo = 2;</code>
       * @param value The currencyTo to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currencyTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currencyTo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrencyTo() {
        
        currencyTo_ = getDefaultInstance().getCurrencyTo();
        onChanged();
        return this;
      }
      /**
       * <code>string currencyTo = 2;</code>
       * @param value The bytes for currencyTo to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currencyTo_ = value;
        onChanged();
        return this;
      }

      private float amount_ ;
      /**
       * <code>float amount = 3;</code>
       * @return The amount.
       */
      public float getAmount() {
        return amount_;
      }
      /**
       * <code>float amount = 3;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(float value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float amount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        
        amount_ = 0F;
        onChanged();
        return this;
      }

      private float result_ ;
      /**
       * <code>float result = 4;</code>
       * @return The result.
       */
      public float getResult() {
        return result_;
      }
      /**
       * <code>float result = 4;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(float value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float result = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        
        result_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConvertCurrencyResponse)
    }

    // @@protoc_insertion_point(class_scope:ConvertCurrencyResponse)
    private static final org.example.stubs.Bank.ConvertCurrencyResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.stubs.Bank.ConvertCurrencyResponse();
    }

    public static org.example.stubs.Bank.ConvertCurrencyResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConvertCurrencyResponse>
        PARSER = new com.google.protobuf.AbstractParser<ConvertCurrencyResponse>() {
      @java.lang.Override
      public ConvertCurrencyResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConvertCurrencyResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConvertCurrencyResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConvertCurrencyResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.stubs.Bank.ConvertCurrencyResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConvertCurrencyRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConvertCurrencyRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConvertCurrencyResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConvertCurrencyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbank.proto\"R\n\026ConvertCurrencyRequest\022\024" +
      "\n\014currencyFrom\030\001 \001(\t\022\022\n\ncurrencyTo\030\002 \001(\t" +
      "\022\016\n\006amount\030\003 \001(\002\"c\n\027ConvertCurrencyRespo" +
      "nse\022\024\n\014currencyFrom\030\001 \001(\t\022\022\n\ncurrencyTo\030" +
      "\002 \001(\t\022\016\n\006amount\030\003 \001(\002\022\016\n\006result\030\004 \001(\0022\250\002" +
      "\n\013BankService\022<\n\007convert\022\027.ConvertCurren" +
      "cyRequest\032\030.ConvertCurrencyResponse\022H\n\021g" +
      "etCurrencyStream\022\027.ConvertCurrencyReques" +
      "t\032\030.ConvertCurrencyResponse0\001\022D\n\rperform" +
      "Stream\022\027.ConvertCurrencyRequest\032\030.Conver" +
      "tCurrencyResponse(\001\022K\n\022fullCurrencyStrea" +
      "m\022\027.ConvertCurrencyRequest\032\030.ConvertCurr" +
      "encyResponse(\0010\001B\023\n\021org.example.stubsb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ConvertCurrencyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConvertCurrencyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConvertCurrencyRequest_descriptor,
        new java.lang.String[] { "CurrencyFrom", "CurrencyTo", "Amount", });
    internal_static_ConvertCurrencyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConvertCurrencyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConvertCurrencyResponse_descriptor,
        new java.lang.String[] { "CurrencyFrom", "CurrencyTo", "Amount", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
